"""Экспорт стратегий в .bat файлы для standalone использования."""
import logging
import shutil
from datetime import datetime
from pathlib import Path

import core.config as cfg
import core.strategies as strats

log = logging.getLogger(__name__)


def export_to_bat(strategy_name: str, hostlist_path: str, output_path: str) -> None:
    """
    Генерирует .bat файл для запуска стратегии без GUI.

    Args:
        strategy_name: Имя стратегии (например, "ALT3")
        hostlist_path: Путь к hostlist.txt
        output_path: Путь для сохранения .bat файла
    """
    args = strats.get_args(strategy_name)
    if not args:
        raise ValueError(f"Стратегия '{strategy_name}' не найдена или пуста")

    # Заменяем абсолютные пути на относительные
    args_str = " ".join(args)
    args_str = args_str.replace(hostlist_path, "hostlist.txt")
    args_str = args_str.replace("{hostlist}", "hostlist.txt")

    # Генерируем содержимое .bat
    bat_content = f"""@echo off
REM Generated by ZapretUI - https://github.com/m1ghtyqxddd/zapret-ui
REM Strategy: {strategy_name}
REM Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

cd /d "%~dp0"

if not exist "winws.exe" (
    echo ERROR: winws.exe not found in current directory
    echo Place winws.exe and hostlist.txt next to this .bat file
    pause
    exit /b 1
)

if not exist "hostlist.txt" (
    echo ERROR: hostlist.txt not found in current directory
    echo Place winws.exe and hostlist.txt next to this .bat file
    pause
    exit /b 1
)

echo Starting Zapret with strategy: {strategy_name}
echo.

winws.exe {args_str}
"""

    # Сохраняем файл
    output_path = Path(output_path)
    output_path.write_text(bat_content, encoding="utf-8")
    log.info("Экспортирован .bat: %s", output_path)


def export_bundle(strategy_name: str, output_dir: str) -> str:
    """
    Создаёт полный bundle: папка с winws.exe, hostlist.txt, start.bat, stop.bat.

    Args:
        strategy_name: Имя стратегии
        output_dir: Директория для создания bundle

    Returns:
        Путь к созданной папке bundle
    """
    output_dir = Path(output_dir)
    bundle_dir = output_dir / f"ZapretUI_Bundle_{strategy_name}"

    # Создаём папку
    bundle_dir.mkdir(parents=True, exist_ok=True)
    log.info("Создаём bundle в: %s", bundle_dir)

    # Копируем winws.exe
    winws_path = Path(cfg.get("winws_path", "bin/winws.exe"))
    if not winws_path.exists():
        # Пробуем относительный путь
        winws_path = Path(__file__).parent.parent / "bin" / "winws.exe"

    if winws_path.exists():
        shutil.copy2(winws_path, bundle_dir / "winws.exe")
        log.info("Скопирован winws.exe")
    else:
        log.warning("winws.exe не найден, bundle будет неполным")

    # Копируем hostlist.txt
    hostlist_path = Path(cfg.get("hostlist_path", "lists/hostlist.txt"))
    if not hostlist_path.exists():
        hostlist_path = Path(__file__).parent.parent / "lists" / "hostlist.txt"

    if hostlist_path.exists():
        shutil.copy2(hostlist_path, bundle_dir / "hostlist.txt")
        log.info("Скопирован hostlist.txt")
    else:
        log.warning("hostlist.txt не найден, bundle будет неполным")

    # Генерируем start.bat
    start_bat = bundle_dir / "start.bat"
    export_to_bat(strategy_name, str(hostlist_path), str(start_bat))

    # Генерируем stop.bat
    stop_bat_content = """@echo off
REM Generated by ZapretUI - https://github.com/m1ghtyqxddd/zapret-ui
REM Stop winws.exe

echo Stopping winws.exe...
taskkill /F /IM winws.exe 2>nul

if %ERRORLEVEL% EQU 0 (
    echo winws.exe stopped successfully
) else (
    echo winws.exe is not running
)

pause
"""
    stop_bat = bundle_dir / "stop.bat"
    stop_bat.write_text(stop_bat_content, encoding="utf-8")
    log.info("Создан stop.bat")

    # Создаём README.txt
    readme_content = f"""Zapret UI Bundle - {strategy_name}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Содержимое:
- winws.exe       - Основной исполняемый файл zapret
- hostlist.txt    - Список доменов для обхода
- start.bat       - Запуск защиты (требует права администратора)
- stop.bat        - Остановка защиты

Использование:
1. Запустите start.bat от имени администратора
2. Для остановки запустите stop.bat

Источник: https://github.com/m1ghtyqxddd/zapret-ui
Оригинальный zapret: https://github.com/bol-van/zapret
"""
    readme = bundle_dir / "README.txt"
    readme.write_text(readme_content, encoding="utf-8")
    log.info("Создан README.txt")

    return str(bundle_dir)
